# Generated by Django 5.2.16 on 2026-07-17 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patterns', '0002_dailypattern_savedpattern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_uk', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_uk', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Категорія блогу',
                'verbose_name_plural': 'Категорії блогу',
            },
        ),
        migrations.CreateModel(
            name='GuestPostSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('proposed_topic', models.CharField(max_length=255)),
                ('proposal_description', models.TextField()),
                ('honeypot', models.CharField(blank=True, help_text='Приховане поле проти автоматичного спаму — має лишатись порожнім.', max_length=255)),
                ('submitter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('new', 'Нова'), ('in_review', 'На розгляді'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], default='new', max_length=20)),
            ],
            options={
                'verbose_name': 'Заявка на гостьовий пост',
                'verbose_name_plural': 'Заявки на гостьові пости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('title_uk', models.CharField(db_index=True, max_length=255, null=True)),
                ('title_en', models.CharField(db_index=True, max_length=255, null=True)),
                ('excerpt', models.TextField(help_text='Короткий опис для карток у списку статей.')),
                ('excerpt_uk', models.TextField(help_text='Короткий опис для карток у списку статей.', null=True)),
                ('excerpt_en', models.TextField(help_text='Короткий опис для карток у списку статей.', null=True)),
                ('body', models.TextField(help_text='HTML-вміст, санітизується при збереженні.')),
                ('body_uk', models.TextField(help_text='HTML-вміст, санітизується при збереженні.', null=True)),
                ('body_en', models.TextField(help_text='HTML-вміст, санітизується при збереженні.', null=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('published', 'Опубліковано')], default='draft', max_length=20)),
                ('post_type', models.CharField(choices=[('editorial', 'Редакційна'), ('guest', 'Гостьова'), ('sponsored', 'Спонсорована')], default='editorial', help_text='Визначає позначку «Партнерський матеріал» для непередакційного типу.', max_length=20)),
                ('guest_author_name', models.CharField(blank=True, help_text='Заповнюється лише для гостьових/спонсорованих публікацій.', max_length=255)),
                ('submitter_contact', models.CharField(blank=True, help_text='Службове поле, не публічне.', max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_title_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_description_uk', models.TextField(blank=True, null=True)),
                ('seo_description_en', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.blogcategory')),
                ('sources', models.ManyToManyField(blank=True, help_text="Обов'язково для статей, що торкаються історичних/символічних тверджень (розділ 4.6 ТЗ).", related_name='blog_posts', to='patterns.source')),
            ],
            options={
                'verbose_name': 'Стаття блогу',
                'verbose_name_plural': 'Статті блогу',
                'ordering': ['-published_at'],
            },
        ),
    ]
