# Generated by Django 5.2.16 on 2026-07-17 16:42

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='body_uk',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='HTML-вміст, санітизується при збереженні.'),
        ),
    ]
