# Generated by Django 5.2.16 on 2026-07-26 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_body_en_remove_blogpost_body_uk_and_more'),
        ('patterns', '0016_kyiv_grape_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='related_region',
            field=models.ForeignKey(blank=True, help_text='Якщо стаття присвячена конкретному регіону - для взаємного перелінкування (SEO-кластер).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='patterns.region'),
        ),
    ]
