# Generated by Django 5.2.16 on 2026-08-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_related_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='target_keyword',
            field=models.CharField(blank=True, help_text='Цільове ключове слово/фраза для цієї статті (SEO).', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='target_keyword_en',
            field=models.CharField(blank=True, help_text='Цільове ключове слово/фраза для цієї статті (SEO).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='target_keyword_uk',
            field=models.CharField(blank=True, help_text='Цільове ключове слово/фраза для цієї статті (SEO).', max_length=255, null=True),
        ),
    ]
