# Generated by Django 5.2.17 on 2026-09-25 15:55

from django.db import migrations, models
from django.db.models import F


def copy_to_uk(apps, schema_editor):
    apps.get_model("blog", "Author").objects.update(name_uk=F("name"), bio_uk=F("bio"))



class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_drop_view_count_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="bio_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="bio_uk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="name_uk",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(copy_to_uk, migrations.RunPython.noop),
    ]
