# Generated by Django 5.2.17 on 2026-09-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_author_translation"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="cover_image_alt",
            field=models.CharField(
                blank=True,
                help_text="Що зображено на обкладинці. Не повторювати заголовок статті.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="cover_image_alt_en",
            field=models.CharField(
                blank=True,
                help_text="Що зображено на обкладинці. Не повторювати заголовок статті.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="cover_image_alt_uk",
            field=models.CharField(
                blank=True,
                help_text="Що зображено на обкладинці. Не повторювати заголовок статті.",
                max_length=255,
                null=True,
            ),
        ),
    ]
