# Generated by Django 5.2.17 on 2026-09-27 19:33

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_author_avatar_webp"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="body_en",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                default="",
                help_text="Англійський текст статті. Порожній - EN-версія не індексується.",
            ),
        ),
    ]
