# Generated by Django 5.2.16 on 2026-07-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Назва джерела — книга, музей, наукова публікація тощо.', max_length=255)),
                ('source_type', models.CharField(choices=[('academic', 'Академічна публікація'), ('museum', 'Музейна колекція'), ('institution', 'Видання культурної інституції'), ('oral_tradition', 'Усна традиція (регіональний фольклор)'), ('other', 'Інше')], help_text='Рівень довіри визначається типом джерела (розділ 4.2 ТЗ).', max_length=20)),
                ('author_or_institution', models.CharField(help_text='Автор чи установа.', max_length=255)),
                ('reference', models.TextField(help_text='URL за наявності, або повний бібліографічний запис для друкованих видань.')),
                ('publication_year', models.PositiveIntegerField(blank=True, help_text="Рік видання чи публікації (необов'язково).", null=True)),
                ('editor_note', models.TextField(blank=True, help_text='Коротке пояснення чому саме це джерело використано, чи є розбіжності з іншими джерелами (розділ 3.4 ТЗ).')),
            ],
            options={
                'verbose_name': 'Джерело',
                'verbose_name_plural': 'Джерела',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(help_text='Назва регіону, наприклад «Полтавщина».', max_length=255)),
                ('name_uk', models.CharField(help_text='Назва регіону, наприклад «Полтавщина».', max_length=255, null=True)),
                ('name_en', models.CharField(help_text='Назва регіону, наприклад «Полтавщина».', max_length=255, null=True)),
                ('symbolism_description', models.TextField(help_text='Розгорнутий опис значення кольорів і мотивів саме цього регіону.')),
                ('symbolism_description_uk', models.TextField(help_text='Розгорнутий опис значення кольорів і мотивів саме цього регіону.', null=True)),
                ('symbolism_description_en', models.TextField(help_text='Розгорнутий опис значення кольорів і мотивів саме цього регіону.', null=True)),
                ('dominant_colors', models.JSONField(help_text='Список кольорових кодів (наприклад, ["#FF6B35", "#004E89"]).')),
                ('shirt_cut_type', models.CharField(help_text='Особливості крою сорочки (наразі інформаційне поле).', max_length=255)),
                ('rotation_order', models.IntegerField(help_text='Позиція регіону в календарній послідовності ротації (розділ 8.3 ТЗ).')),
                ('is_active', models.BooleanField(default=True, help_text='Дозволяє тимчасово виключити регіон з ротації без видалення даних.')),
                ('verification_status', models.CharField(choices=[('pending', 'На перевірці'), ('verified', 'Верифіковано'), ('needs_review', 'Потребує перегляду')], default='pending', help_text='Редакційний статус (розділ 4.4 ТЗ).', max_length=20)),
                ('sources', models.ManyToManyField(help_text="Обов'язкове — порожній перелік джерел блокує публікацію (розділ 4.4 ТЗ).", to='patterns.source')),
            ],
            options={
                'verbose_name': 'Регіон',
                'verbose_name_plural': 'Регіони',
                'ordering': ['rotation_order'],
            },
        ),
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Назва мотиву, наприклад «Ромб», «Барвінок».', max_length=255)),
                ('name_uk', models.CharField(help_text='Назва мотиву, наприклад «Ромб», «Барвінок».', max_length=255, null=True)),
                ('name_en', models.CharField(help_text='Назва мотиву, наприклад «Ромб», «Барвінок».', max_length=255, null=True)),
                ('meaning_description', models.TextField(help_text='Коротке пояснення що символізує мотив.')),
                ('meaning_description_uk', models.TextField(help_text='Коротке пояснення що символізує мотив.', null=True)),
                ('meaning_description_en', models.TextField(help_text='Коротке пояснення що символізує мотив.', null=True)),
                ('geometry_parameters', models.JSONField(help_text='Базові координати, правила симетрії, застосовні групи симетрії (розділ 3.3, 8.4 ТЗ).')),
                ('verification_status', models.CharField(choices=[('pending', 'На перевірці'), ('verified', 'Верифіковано'), ('needs_review', 'Потребує перегляду')], default='pending', help_text='Той самий принцип, що й у Region (розділ 3.3, 4.4 ТЗ).', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('compatible_regions', models.ManyToManyField(blank=True, help_text='Які регіони типово використовують цей мотив.', related_name='compatible_motifs', to='patterns.region')),
                ('sources', models.ManyToManyField(help_text="Обов'язкове — той самий принцип, що й у Region (розділ 4.4 ТЗ).", to='patterns.source')),
            ],
            options={
                'verbose_name': 'Мотив',
                'verbose_name_plural': 'Мотиви',
            },
        ),
    ]
