# Generated by Django 5.2.16 on 2026-07-10 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, help_text='Один патерн на календарний день.', unique=True)),
                ('seed', models.CharField(help_text='Детермінований seed на основі дати (розділ 8.2 ТЗ).', max_length=255)),
                ('algorithm_version', models.PositiveIntegerField(help_text="Критично для відтворюваності — історичні патерни лишаються прив'язаними до версії, якою вони були створені (розділ 8.8 ТЗ).")),
                ('svg_content', models.TextField(help_text='Готовий результат генерації — текстовий XML-вміст SVG.')),
                ('generation_status', models.CharField(choices=[('success', 'Успішно'), ('fallback', 'Помилка, застосовано резервний варіант')], default='success', help_text='Службове поле для діагностики (розділ 8.6 ТЗ).', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('motifs_used', models.ManyToManyField(blank=True, help_text='Які саме мотиви увійшли до патерну — для аналітики й фільтрів.', related_name='daily_patterns', to='patterns.motif')),
                ('region', models.ForeignKey(help_text="Заборона видалення регіону поки є пов'язані патерни.", on_delete=django.db.models.deletion.PROTECT, related_name='daily_patterns', to='patterns.region')),
            ],
            options={
                'verbose_name': 'Щоденний патерн',
                'verbose_name_plural': 'Щоденні патерни',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SavedPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='patterns.dailypattern')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Збережений патерн',
                'verbose_name_plural': 'Збережені патерни',
                'constraints': [models.UniqueConstraint(fields=('user', 'pattern'), name='unique_user_pattern')],
            },
        ),
    ]
