# Generated by Django 5.2.16 on 2026-08-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0016_kyiv_grape_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='target_keyword',
            field=models.CharField(blank=True, help_text='Цільове ключове слово/фраза для цієї сторінки (SEO).', max_length=255),
        ),
        migrations.AddField(
            model_name='region',
            name='target_keyword_en',
            field=models.CharField(blank=True, help_text='Цільове ключове слово/фраза для цієї сторінки (SEO).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='target_keyword_uk',
            field=models.CharField(blank=True, help_text='Цільове ключове слово/фраза для цієї сторінки (SEO).', max_length=255, null=True),
        ),
    ]
