# Generated by Django 5.2.16 on 2026-08-05 13:27

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0018_copy_uk_description_before_ckeditor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='symbolism_description_en',
        ),
        migrations.RemoveField(
            model_name='region',
            name='symbolism_description_uk',
        ),
        migrations.AlterField(
            model_name='region',
            name='symbolism_description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Розгорнутий опис значення кольорів і мотивів саме цього регіону.'),
        ),
    ]
