# Generated by Django 5.2.16 on 2026-08-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0019_remove_region_symbolism_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Опис сторінки для пошукових систем (SEO). Порожнє - береться з опису символіки.', max_length=160),
        ),
        migrations.AddField(
            model_name='region',
            name='seo_description_en',
            field=models.CharField(blank=True, help_text='Опис сторінки для пошукових систем (SEO). Порожнє - береться з опису символіки.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='seo_description_uk',
            field=models.CharField(blank=True, help_text='Опис сторінки для пошукових систем (SEO). Порожнє - береться з опису символіки.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Заголовок сторінки для пошукових систем. Автоматично додає: - VyshyvankaDaily', max_length=70),
        ),
        migrations.AddField(
            model_name='region',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text='Заголовок сторінки для пошукових систем. Автоматично додає: - VyshyvankaDaily', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='seo_title_uk',
            field=models.CharField(blank=True, help_text='Заголовок сторінки для пошукових систем. Автоматично додає: - VyshyvankaDaily', max_length=70, null=True),
        ),
    ]
