# Generated by Django 5.2.16 on 2026-08-05 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0020_region_seo_description_region_seo_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail_url', models.URLField(help_text='Маленьке зображення для плівки мініатюр на сторінці регіону.')),
                ('image_url', models.URLField(help_text='Повнорозмірне зображення, що відкривається по кліку.')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('caption_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('caption_en', models.CharField(blank=True, max_length=255, null=True)),
                ('source_note', models.CharField(blank=True, help_text='Джерело/ліцензія фото - автор чи звідки взято. Перевір права на використання перед публікацією.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='patterns.region')),
            ],
            options={
                'verbose_name': 'Фото регіону',
                'verbose_name_plural': 'Фото регіону',
                'ordering': ['order', 'id'],
            },
        ),
    ]
