# Generated by Django 5.2.16 on 2026-08-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0021_regionphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='shirt_cut_type',
            field=models.CharField(blank=True, help_text='Особливості крою сорочки (наразі інформаційне поле).', max_length=255),
        ),
        migrations.AlterField(
            model_name='regionphoto',
            name='source_note',
            field=models.CharField(blank=True, help_text='Джерело/ліцензія фото - автор чи звідки взято. Перевір права на використання.', max_length=255),
        ),
    ]
