# Generated by Django 5.2.17 on 2026-09-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Фаза 1 з 2: поле зникає з моделі, колонка лишається з DB default 0,
    щоб стара версія коду працювала під час деплою. Колонку видалить фаза 2.
    """

    dependencies = [
        ("patterns", "0022_alter_region_shirt_cut_type_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterField(
                    model_name="dailypattern",
                    name="view_count",
                    field=models.PositiveIntegerField(default=0, db_default=0),
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="dailypattern",
                    name="view_count",
                ),
            ],
        ),
    ]
