# Generated by Django 5.2.17 on 2026-09-25 14:24

import apps.patterns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patterns", "0023_remove_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="dominant_colors",
            field=models.JSONField(
                help_text='Список кольорових кодів (наприклад, ["#FF6B35", "#004E89"]).',
                validators=[apps.patterns.models.validate_hex_colors],
            ),
        ),
    ]
