# Generated by Django 5.2.17 on 2026-09-25 14:26

import django_ckeditor_5.fields
from django.db import migrations
from django.db.models import F


def copy_to_uk(apps, schema_editor):
    Region = apps.get_model("patterns", "Region")
    Region.objects.update(symbolism_description_uk=F("symbolism_description"))


class Migration(migrations.Migration):

    dependencies = [
        ("patterns", "0024_validate_dominant_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="symbolism_description_en",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="Розгорнутий опис значення кольорів і мотивів саме цього регіону.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="symbolism_description_uk",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="Розгорнутий опис значення кольорів і мотивів саме цього регіону.",
                null=True,
            ),
        ),
        migrations.RunPython(copy_to_uk, migrations.RunPython.noop),
    ]
