# Generated by Django 5.2.17 on 2026-09-27 10:20

import apps.patterns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patterns", "0027_motif_dash_to_hyphen"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="accent_colors",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Кольори, що також трапляються. Лише для показу, на генерацію не впливають.",
                validators=[apps.patterns.models.validate_hex_colors],
            ),
        ),
    ]
