# Generated by Django 5.2.17 on 2026-09-27 10:47

import apps.patterns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patterns", "0030_kyiv_honchar_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="generator_only_colors",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Кольори генератора без підтвердження в джерелах: на сторінці не показуються.",
                validators=[apps.patterns.models.validate_hex_colors],
            ),
        ),
    ]
