# Generated by Django 5.2.17 on 2026-09-25 15:55

from django.db import migrations, models
from django.db.models import F


def copy_to_uk(apps, schema_editor):
    apps.get_model("pages", "FAQCategory").objects.update(name_uk=F("name"))



class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_faq_repeat_wording"),
    ]

    operations = [
        migrations.AddField(
            model_name="faqcategory",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="faqcategory",
            name="name_uk",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(copy_to_uk, migrations.RunPython.noop),
    ]
